apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: cs4300piazza
  namespace: default
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: cs4300piazza
    spec:
      containers:
      - name: cs4300piazza
        image: mb2363/cs4300piazza:latest
        imagePullPolicy: Always
        ports:
        - name: https
          containerPort: 5000
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: cs4300piazza
spec:
  type: ClusterIP
  ports:
  - name: https
    port: 443
    targetPort: https
  selector:
    app: cs4300piazza
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pdf-viewer
  namespace: ingress-basic
  annotations:
    kubernetes.io/tls-acme: 'true'
    kubernetes.io/ingress.class: nginx
    kubernetes.io/ingress.allow-http: "false"
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    certmanager.k8s.io/acme-challenge-type: dns01
    certmanager.k8s.io/acme-dns01-provider: azure-dns
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 200m
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  tls:
  - hosts:
    - demo-pdf-viewer.eastus.cloudapp.azure.com
    secretName: tls-secret
  rules:
  - host: demo-pdf-viewer.eastus.cloudapp.azure.com
    http:
      paths:
      - path: /?(.*)
        backend:
          serviceName: pdf-viewer
          servicePort: 443
